name: PointNavResNetLstmPolicy
action_distribution_type: categorical
action_dist:
  use_log_std: True
  use_std_param: True
  std_init: -1
vc1_config:
  is_2d_output: False
  avg_pool_size: 2
training_precision_config:
  visual_encoder: float16
